### ISSUE TITLE
 Codeium Server Crashed

### ISSUE THREAD

**Issue by AppleLAN** [Exafunction/codeium.nvim#179]
Hi ! first of all... I LOVE Codeium, moving on:

Since the last update I can't run it !

Everytime a new auto complete tries to run, I'm being received with a "Codeium server crashed" message and an empty message "[codeium/codeium.log] }"

I can't seem to find the error location, I'm using LazyVim, tried custom plugin installation and also with LazyExtras, same error.

![324250946-ee300ddf-29f8-4616-8beb-d312243601cd](https://github.com/Exafunction/codeium.nvim/assets/6935240/e6e85156-6e22-47ed-acac-d4ca7b93ec94)
![324250745-5262dc0c-66da-4d5f-bb84-ae2af0d99fb8](https://github.com/Exafunction/codeium.nvim/assets/6935240/de7569c0-c1dc-4fbe-91fa-9ea945590b18)

**Comment by Sazzad-Anwar** [comment]
I am also facing the same issue. I am not getting any auto complete suggestion and after a while just getting crashed notification.

**Comment by nepta1998** [comment]
I am having the same problem when I modify a very large file and it gives me these errors:

![Screenshot from 2024-04-22 10-46-12](https://github.com/Exafunction/codeium.nvim/assets/36112164/42b6a09a-7227-41e2-abfe-a5f0b2610f13)


[WARN  lun 22 abr 2024 10:39:17] /home/neptali/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:314: failed to cancel in-flight request {
  code = 0,
  out = '{"code":"unknown","message":"no session for {apiKey:<apikey> sessionId:}"}',
  response = {
    body = '{"code":"unknown","message":"no session for {apiKey: <apikey> sessionId:}"}',
    exit = 0,
    headers = { "Accept-Encoding: gzip", "Content-Type: application/json", "Vary: Origin", "Date: Mon, 22 Apr 2024 14:39:09 GMT", "Content-Length: 102", "", "" },
    status = 500
  },
  status = 500
}
[ERROR lun 22 abr 2024 10:43:08] /home/neptali/.local/share/nvim/lazy/codeium.nvim/lua/codeium/notify.lua:14: codeium server crashed:  {
  code = 1
}

**Comment by amoschristian** [comment]
@nepta1998 yeah i had this error as well, exactly the same, i dont really know what to do with the issue for now

**Comment by amoschristian** [comment]
> In recent update, I've added "other_documents" argument for GetCompletion request, that is attaching buffers content during request to Codeium Server. So, it is possible that too much data are sending to the server. Could you try to comment out this line https://github.com/Exafunction/codeium.nvim/blob/main/lua/codeium/api.lua#L328 and check if it will improve stability?

I just tried it and i dont think it help in any way, still same error

btw the file that i open is a 
~250KB - 3500 line JSON file

but with smaller line of code its working

**Comment by aliaksandr-trush** [comment]
> > In recent update, I've added "other_documents" argument for GetCompletion request, that is attaching buffers content during request to Codeium Server. So, it is possible that too much data are sending to the server. Could you try to comment out this line https://github.com/Exafunction/codeium.nvim/blob/main/lua/codeium/api.lua#L328 and check if it will improve stability?
> 
> I just tried it and i dont think it help in any way, still same error
> 
> btw the file that i open is a ~250KB - 3500 line JSON file
> 
> but with smaller line of code its working

In this case it could be related to server version that was updated in https://github.com/Exafunction/codeium.nvim/commit/4d4e2a6cdc35cdd344d1dcc8ae7846aca6db897d

**Comment by amoschristian** [comment]
@aliaksandr-trush so in other words, is there any way to fix this? i mean there must be a lot of people out there who gonna has this issue right

**Comment by aliaksandr-trush** [comment]
> @aliaksandr-trush so in other words, is there any way to fix this? i mean there must be a lot of people out there who gonna has this issue right

JFYI I am not Codeium developer :)

Also, I am unable to reproduce the issue on my projects.

But definitely it will be easier to resolve the issue if somebody will provide exact steps to reproduce:
1. Project URL that is failing
2. Files where Neovim is failing

If it is failing on private projects, that it could be useful to understand what change introduced this issue:
1. Changes in codeium.nvim plugin
2. or Language server version change

**Comment by mitya-murakhouski** [comment]
Having same issue with yml files. Have to restart vim all the time

**Comment by mrloop** [comment]
I ran nvim with `CODEIUM_DEBUG=true` and got the log below. It suggested that file limit too low `server.go:252] Failed to start file watcher: too many open files`. Increasing limits and codeium no longer crashing for me. Used instructions [here](https://www.phind.com/search?cache=tiom44lcutuvkrv9b9yzr28m) to increase limits

```log 
[codeium/codeium.log] [DEBUG 12:47:50] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:50.198170 360769 main.go:245] Waiting for random port file in /tmp/nvim.ewan/6IgGIX/5codeium/manager/child_
random_port_1720266470197728640_374151501641376062 to be created
[codeium/codeium.log] [DEBUG 12:47:50] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:50.355364 361230 main.go:543] Starting language server process with pid 361230
[codeium/codeium.log] [DEBUG 12:47:50] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:50.355409 361230 server.go:158] Language server will attempt to listen on host 127.0.0.1
[codeium/codeium.log] [DEBUG 12:47:50] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:50.355513 361230 server.go:165] Language server listening on random port at 43097
[codeium/codeium.log] [DEBUG 12:47:50] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:50.355549 361230 proxy.go:113] proxyplease.proxy> No proxy provided. Attempting to infer from system.
[codeium/codeium.log] [DEBUG 12:47:50] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:50.355562 361230 proxy.go:113] proxyplease.proxy> No proxy could be determined. Assuming a direct connectio
n.
[codeium/codeium.log] [DEBUG 12:47:50] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:50.355580 361230 client.go:589] [DEBUG] GET https://server.codeium.com:443/exa.api_server_pb.ApiServerServi
ce/GetCompletions
[codeium/codeium.log] [DEBUG 12:47:50] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:50.763755 361230 unleash.go:86] Initializing Unleash
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.171832 361230 unleash.go:106] Successfully initialized Unleash
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.184298 361230 server.go:346] Successfully created API server client
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.197418 361230 server.go:360] Successfully created API streaming client
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.275853 361230 server.go:369] Successfully initialized tokenizer
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.275990 361230 search_provider.go:169] Using database at /home/ewan/.codeium/database/default/2/MODEL_EMB
ED_6591
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.277047 361230 search_provider.go:181] Successfully created embedding search database
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.277429 361230 search_provider.go:229] Successfully created embedding search provider
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.277443 361230 server.go:455] Successfully created exact search provider
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: E0706 12:47:51.278283 361230 unleash.go:57] Unleash error: Version string empty
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: E0706 12:47:51.278358 361230 unleash.go:57] Unleash error: Version string empty
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: E0706 12:47:51.278436 361230 unleash.go:57] Unleash error: Version string empty
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: E0706 12:47:51.278454 361230 unleash.go:57] Unleash error: Version string empty
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.283593 361230 server.go:483] Successfully created completion provider
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.358541 361230 server.go:574] Child process attempting to acquire lock file /tmp/nvim.ewan/6IgGIX/5codeiu
m/manager/locks/child_lock_1720266470197791080_9058985203110864253
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.358615 361230 server.go:584] Child process acquired lock file /tmp/nvim.ewan/6IgGIX/5codeium/manager/loc
ks/child_lock_1720266470197791080_9058985203110864253
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: E0706 12:47:51.363918 361230 server.go:252] Failed to start file watcher: too many open files
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: panic: runtime error: invalid memory address or nil pointer dereference
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x716aa45]
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769:
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: goroutine 32 [running]:
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: github.com/Exafunction/Exafunction/exa/language_server/file_watcher.(*FileWatcher).ListenAndForwardEvents(0x0)
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: ^Iexa/language_server/file_watcher/file_watcher.go:84 +0x25
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: created by github.com/Exafunction/Exafunction/exa/language_server.CreateLanguageServerAndServe in goroutine 1
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: ^Iexa/language_server/server.go:255 +0x9cd
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.403938 360769 main.go:281] Language server manager found random server port 43097
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.403972 360769 main.go:282] Language server manager found random lsp port 42101
[codeium/codeium.log] [DEBUG 12:47:51] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:51.403985 360769 main.go:289] Language server manager attempting to connect to language server at 127.0.0.1
:43097
[codeium/codeium.log] [DEBUG 12:47:53] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: E0706 12:47:53.404216 360769 main.go:328] Failed to connect to language server at addr 127.0.0.1:43097 after 2s and 4 t
ries and last error - unavailable: dial tcp 127.0.0.1:43097: connect: connection refused
[codeium/codeium.log] [DEBUG 12:47:53] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: I0706 12:47:53.404702 360769 cmd_wrapper.go:267] LanguageServer exited with: exit code: 2
[codeium/codeium.log] [DEBUG 12:47:53] /home/ewan/.local/share/nvim/lazy/codeium.nvim/lua/codeium/api.lua:210: 360769: F0706 12:47:53.404890 360769 main.go:169] Exceeded maximum number of connection failures 4
codeium server crashed
```

**Comment by pqn** [comment]
@mrloop thanks for the report, I'll make a change to not crash in such circumstances for the next release. If anyone else can get logs, I can help figure out the reason for their crashes.
