### ISSUE TITLE
Codeium Chat doesn't work in Neovim

### ISSUE THREAD

**Issue by brianhuster** [Exafunction/codeium.nvim#238]
I encounter this problem when running `:Codeium Chat`. It throws these errors
```
Error executing luv callback:
....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:300: post http://127.0.0.1:38731/exa.language_server_pb.LanguageServerService/AddTrackedWorkspace - curl error exit_code=52 stderr={ "curl: (52) Empty reply from server" }
stack traceback:
	[C]: in function 'error'
	....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:300: in function '_user_on_exit'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:241: in function '_shutdown'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:48: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:39>
```

I run `:che codeium` and here is what I get 
```
Codeium: checking Codeium server status ~
- OK API key properly loaded
- Checking server status
- OK Server is healthy on port: 38731
- Language Server binary: /home/brianhuster/.cache/nvim/codeium/bin/1.20.6/language_server_linux_x64
- Last heartbeat: 10/04/24 23:51:59
- OK Heartbeat ok
```

So basically health check says server is healthy on port 38731, but plenary.nvim says that server sent empty reply.

**Comment by dimfeld** [comment]
Seeing this in the logs, with latest plugin code and LSP 1.20.9. Works fine in `codeium.vim` but I havent' figured out what the difference is yet. The AddTrackedWorkspace call itself is passing the same payload.

```
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: panic: runtime error: invalid memory address or nil pointer dereference
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: [signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x103476114]
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: 
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: goroutine 170 [running]:
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: github.com/Exafunction/Exafunction/exa/fs.Path.Stat({{}, {0x0?, 0x0?}, {0x0?, 0x14000fdd000?}})
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: 	exa/fs/path.go:101 +0x24
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: github.com/Exafunction/Exafunction/exa/fs/workspace_manager.(*WorkspaceInfoManager).matchingTrackedWorkspaces(0x140002f8f50, {{0x0?, 0x0?}})
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: 	exa/fs/workspace_manager/workspace_manager.go:757 +0x48
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: github.com/Exafunction/Exafunction/exa/fs/workspace_manager.(*WorkspaceInfoManager).StartTrackingPath(0x140002f8f50, {{}, {0x0?, 0x0?}, {0x0?, 0x102ee5b40?}}, {0x104ccc726, 0x26})
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: 	exa/fs/workspace_manager/workspace_manager.go:306 +0x80
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: github.com/Exafunction/Exafunction/exa/language_server/context_module.(*ContextModule).notifyOfFile.func1()
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: 	exa/language_server/context_module/context_module.go:1652 +0x40
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: created by github.com/Exafunction/Exafunction/exa/language_server/context_module.(*ContextModule).notifyOfFile in goroutine 168
[DEBUG Sun Oct  6 15:44:46 2024] /Users/dimfeld/Documents/projects/codeium.nvim/lua/codeium/api.lua:256: 99204: 	exa/language_server/context_module/context_module.go:1651 +0xd4
```

**Comment by flleonx** [comment]
Hey, when do you plan to merge this fix? Waiting for it 😄

**Comment by brianhuster** [comment]
>  I havent' figured out what the difference is yet. 

The first difference I realized is that codeium.nvim uses plenary.nvim for making http request, while codeium.vim just uses the command `curl` from terminal

**Comment by yummycheese** [comment]
Running into something similar. 

I'm looking at the codium log and verifying that the chat process is starting when I launch vim. 
Verified that the process is there and is listening on the correct port.

As soon as I execute :Codeium Chat. I get sent to my web browser. URL looks good. Has the right tcp port. But then I notice the chat process that was listening on that port has died. Seems like as soon as I attempt to use it. Its crashing.

**Comment by dimfeld** [comment]
The PR linked above fixes it. Just waiting for them to merge…

**Comment by yummycheese** [comment]
Thanks for the PR. I updated my local plugin and can confirm that it fixed the issue. Executing :Codeium Chat works as expected now
